/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as WhyFensivoRouteImport } from './routes/why-fensivo'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CompanyAboutRouteImport } from './routes/company.about'
import { Route as CompanyPartnersRouteImport } from './routes/company.partners'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersSlugRouteImport } from './routes/customers.$slug'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformFensivo360RouteImport } from './routes/platform.fensivo-360'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesCategoryRouteImport } from './routes/resources.$category'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as ResourcesArticleSlugRouteImport } from './routes/resources.article.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyFensivoRoute = WhyFensivoRouteImport.update({
  id: '/why-fensivo',
  path: '/why-fensivo',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPartnersRoute = CompanyPartnersRouteImport.update({
  id: '/company/partners',
  path: '/company/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersSlugRoute = CustomersSlugRouteImport.update({
  id: '/customers/$slug',
  path: '/customers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformFensivo360Route = PlatformFensivo360RouteImport.update({
  id: '/platform/fensivo-360',
  path: '/platform/fensivo-360',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCategoryRoute = ResourcesCategoryRouteImport.update({
  id: '/resources/$category',
  path: '/resources/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesArticleSlugRoute = ResourcesArticleSlugRouteImport.update({
  id: '/resources/article/$slug',
  path: '/resources/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/why-fensivo': typeof WhyFensivoRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/customers/$slug': typeof CustomersSlugRoute
  '/platform/fensivo-360': typeof PlatformFensivo360Route
  '/resources/$category': typeof ResourcesCategoryRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/company/': typeof CompanyIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/resources/article/$slug': typeof ResourcesArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/why-fensivo': typeof WhyFensivoRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/customers/$slug': typeof CustomersSlugRoute
  '/platform/fensivo-360': typeof PlatformFensivo360Route
  '/resources/$category': typeof ResourcesCategoryRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/company': typeof CompanyIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/resources/article/$slug': typeof ResourcesArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/why-fensivo': typeof WhyFensivoRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/customers/$slug': typeof CustomersSlugRoute
  '/platform/fensivo-360': typeof PlatformFensivo360Route
  '/resources/$category': typeof ResourcesCategoryRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/company/': typeof CompanyIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/resources/article/$slug': typeof ResourcesArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/demo'
    | '/login'
    | '/pricing'
    | '/why-fensivo'
    | '/company/about'
    | '/company/partners'
    | '/customers/$slug'
    | '/platform/fensivo-360'
    | '/resources/$category'
    | '/solutions/$slug'
    | '/company/'
    | '/customers/'
    | '/platform/'
    | '/resources/'
    | '/solutions/'
    | '/resources/article/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/demo'
    | '/login'
    | '/pricing'
    | '/why-fensivo'
    | '/company/about'
    | '/company/partners'
    | '/customers/$slug'
    | '/platform/fensivo-360'
    | '/resources/$category'
    | '/solutions/$slug'
    | '/company'
    | '/customers'
    | '/platform'
    | '/resources'
    | '/solutions'
    | '/resources/article/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/demo'
    | '/login'
    | '/pricing'
    | '/why-fensivo'
    | '/company/about'
    | '/company/partners'
    | '/customers/$slug'
    | '/platform/fensivo-360'
    | '/resources/$category'
    | '/solutions/$slug'
    | '/company/'
    | '/customers/'
    | '/platform/'
    | '/resources/'
    | '/solutions/'
    | '/resources/article/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  WhyFensivoRoute: typeof WhyFensivoRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyPartnersRoute: typeof CompanyPartnersRoute
  CustomersSlugRoute: typeof CustomersSlugRoute
  PlatformFensivo360Route: typeof PlatformFensivo360Route
  ResourcesCategoryRoute: typeof ResourcesCategoryRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  ResourcesArticleSlugRoute: typeof ResourcesArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-fensivo': {
      id: '/why-fensivo'
      path: '/why-fensivo'
      fullPath: '/why-fensivo'
      preLoaderRoute: typeof WhyFensivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/partners': {
      id: '/company/partners'
      path: '/company/partners'
      fullPath: '/company/partners'
      preLoaderRoute: typeof CompanyPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$slug': {
      id: '/customers/$slug'
      path: '/customers/$slug'
      fullPath: '/customers/$slug'
      preLoaderRoute: typeof CustomersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/fensivo-360': {
      id: '/platform/fensivo-360'
      path: '/platform/fensivo-360'
      fullPath: '/platform/fensivo-360'
      preLoaderRoute: typeof PlatformFensivo360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$category': {
      id: '/resources/$category'
      path: '/resources/$category'
      fullPath: '/resources/$category'
      preLoaderRoute: typeof ResourcesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/article/$slug': {
      id: '/resources/article/$slug'
      path: '/resources/article/$slug'
      fullPath: '/resources/article/$slug'
      preLoaderRoute: typeof ResourcesArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  WhyFensivoRoute: WhyFensivoRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyPartnersRoute: CompanyPartnersRoute,
  CustomersSlugRoute: CustomersSlugRoute,
  PlatformFensivo360Route: PlatformFensivo360Route,
  ResourcesCategoryRoute: ResourcesCategoryRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  ResourcesArticleSlugRoute: ResourcesArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
